<div class="image">

  <img style="float: right;" src="https://pku.org.uk/head.png" width="45%" align="right">
      <h4>
          <p style="font-size:25pt">UK19B307 AI Analytics</p>
          <p style="font-size:15pt">Quiz 4</p>
      </h4>
<h5>
    <p> Peking University</p>
    <p> Demonstrable Labs</p>
</h5>
</div>

### Please doule click this block and enter your name / ID:

- Name: LIU YUJIE
- ID: 1901212616

In [1]:
import numpy as np
import pandas as pd

<div class="alert alert-warning">
<b>QUESTION 1: </b> 

1, Define a list: `persons = [ "John", "Marissa", "Pete", "Dayton" ]`

2, Print the first two elements by slicing the list. The expected output is: `['John', 'Marissa']`
</div>

In [6]:
persons = [ "John", "Marissa", "Pete", "Dayton" ]
persons[0:2]

['John', 'Marissa']

<div class="alert alert-warning">
<b>QUESTION 2: </b> 

Using a `while` loop, print integers from range `25` to `70`. The integers should be divisible by 3. The expected output is:
```
27
30
33
36
39
42
45
48
51
54
57
60
63
66
69```

In [9]:
i=25
while True:
    i += 1
    if i%3 == 0:
        print(i)
    if i == 70:
        break

27
30
33
36
39
42
45
48
51
54
57
60
63
66
69


<div class="alert alert-warning">
<b>QUESTION 3: </b> 

1, Define a list: `list_x = ['7', '1', '2', '5']`
    
2, Use list comprehension to convert the strings in the list to integers. Print the updated list, the expected output is: `[7, 1, 2, 5]`
</div>

In [15]:
list_x = ['7', '1', '2', '5']
list_x = [int(i) for i in list_x]
print (list_x)

[7, 1, 2, 5]


<div class="alert alert-warning">

<b>QUESTION 4:</b>

1, Create a function called `common` that takes two lists as arguments. The function would return a **list** with common characters from the input lists.

2, Define two lists:

```python
list_1 = [1,2,3]
list_2 = [2,3,4]
```
    
3, Call the function with the two lists, print the result, the expected output is: 
 
```
[2, 3]```
 
</div>

In [24]:
def common(list_1,list_2):
    return list_1 & list_2

In [26]:
list_1 = [1,2,3]
list_2 = [2,3,4]
common(list_1,list_2)

<div class="alert alert-warning">
<b>QUESTION 5:</b> 
    
1, Define an array: `arr_nums = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21])`
 
2, Calculate the cumulative sum of the array and print the result. The expected output is: `[  1   4   9  16  25  36  49  64  81 100 121]`

</div>

In [31]:
arr_nums = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21])
print(arr_nums.cumsum())

[  1   4   9  16  25  36  49  64  81 100 121]


<div class="alert alert-warning">
<b>QUESTION 6:</b>
  
Please fill the gaps in the code below so that it prints all the prime&ast; numbers in range from `2` to `50`.

```python
for possiblePrime in _______:
    isPrime = True
    for num in range(2, possiblePrime):
        if possiblePrime % num == 0:
            isPrime = False 
    if _______:
        print(________)  
```
    
&ast; A prime number has to be a positive integer, which is divisible by exactly two integers ($1$ and itself), also $1$ is not a prime number.

The expected output of the code is:
```
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47```
</div>

In [32]:
for possiblePrime in range(2,51):
    isPrime = True
    for num in range(2, possiblePrime):
        if possiblePrime % num == 0:
            isPrime = False 
    if num>0:
        print(num)

NameError: name 'num' is not defined

<div class="alert alert-warning">
<b>QUESTION 7:</b>
    
1, Define two DataFrames: 

```python
df_1 = pd.DataFrame({'name': ['Jason', 'Tina', 'Jake', 'Amy'],
                     'age': [32, 28, 23, 33],
                     'TestScore': [70, 92, 88, 65]})
df_2 = pd.DataFrame({'name': ['Tim', 'Alice'],
                     'age': [21, 33],
                     'TestScore': [81, 83]})```
    
2, Define a new DataFrame called `df_3` which concatenates `df_1` and `df_2`. Display `df_3`, the expected output is:
    
<img src="//i.imgur.com/KYsFGl9.png" height="20%" width="20%">
</div>

In [33]:
df_1 = pd.DataFrame({'name': ['Jason', 'Tina', 'Jake', 'Amy'],
                     'age': [32, 28, 23, 33],
                     'TestScore': [70, 92, 88, 65]})
df_2 = pd.DataFrame({'name': ['Tim', 'Alice'],
                     'age': [21, 33],
                     'TestScore': [81, 83]})

In [37]:
df_3 = pd.concat([df_1,df_2],ignore_index=True)
df_3

TestScore  age   name
0         70   32  Jason
1         92   28   Tina
2         88   23   Jake
3         65   33    Amy
4         81   21    Tim
5         83   33  Alice

<div class="alert alert-warning">
<b>QUESTION 8:</b>
    
Sort the DataFrame `df_3` by column `age`, then by column `TestScore`, both with descending orders. Display the updated DataFrame, the expected output is:

<img src="//i.imgur.com/5sAfdZV.png" height="20%" width="20%">

</div>

In [48]:
df_3 = df_3.sort_values(['age','TestScore'],ascending=False)
df_3

TestScore  age   name group
5         83   33  Alice     A
3         65   33    Amy     A
0         70   32  Jason     A
1         92   28   Tina     A
2         88   23   Jake     A
4         81   21    Tim     A

<div class="alert alert-warning">
<b>QUESTION 9:</b>
    
Create a new column called `group` in `df_3`, the value in the column is `A` if `age` is lager than 30 and `B` otherwise. Display the new DataFrame, the expected output is: 

<img src="//i.imgur.com/nzbxPbi.png" height="20%" width="20%">

</div>

In [47]:
df_3['group']="A"  
df_3['group']="B" if df_3['age']>30
df_3

SyntaxError: invalid syntax (<ipython-input-47-40f47439cea9>, line 2)

<div class="alert alert-warning">
<b>QUESTION 10:</b>
    
Reset the index of `df_3` so that it ranges from 0 to 5. Display the new DataFrame, the expected output is:
    
<img src="//i.imgur.com/Le4KHUu.png" height="20%" width="20%">    

</div>

In [54]:
df_3.reset_index('0','1','2','3','4','5')

TypeError: reset_index() takes from 1 to 6 positional arguments but 7 were given

<div class="alert alert-warning">
<b>QUESTION 11:</b>
    
1, Define an array: `arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`

2, Extract all odd numbers from `arr` as a array. Print the result, the expected output is: `[1 3 5 7 9]`
</div>

In [55]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


<div class="alert alert-warning">
<b>QUESTION 12:</b>
    
Please fill the gaps in the code below so that the output of it would be `LeafRed`.
    
```python
Types = ['Leaf', 'Fire', 'Water']
Colours = ['Green', 'Red', 'Blue']
print('______'.format(Colours[1], Types[0]))
```

</div>

In [56]:
Types = ['Leaf', 'Fire', 'Water']
Colours = ['Green', 'Red', 'Blue']
print('{1}{0}'.format(Colours[1], Types[0]))

LeafRed


<div class="alert alert-warning">
<b>QUESTION 13:</b>
    
1, Define an array: `arr = np.arange(24).reshape(6,4)`

2, Print the array below by indexing `arr`.

```    
[[ 9 10]
 [13 14]]```

</div>

In [59]:
arr = np.arange(24).reshape(6,4)
arr[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

<div class="alert alert-warning">
<b>QUESTION 14:</b>
    
1, Define a string: `random_str = 'erdXxorPQjFXXyaxoJQI'`

2, Calculate the number of `X` and `x` (upper and lower case letters) in the string and print the result. The expected output is `5`.
</div>

In [64]:
 random_str = 'erdXxorPQjFXXyaxoJQI'
 random_str.count('x')

2

<div class="alert alert-warning">
<b>QUESTION 15: </b> 

1, Define a DataFrame:

```python
customer_data = pd.DataFrame(
    {'customer_id': [3, 2, 9, 4, 5, 8, 10, 1, 15, 11, 6, 7, 12, 14, 13],
     'gender': ['M','F','M','M','F','M','F','F','F','F','F','M','M','M','F'],
     'customer_age': [22, 21, 35, 40, 22, 28, 25, 43, 33, 37, 27, 30, 20, 50, 32],
     'post_code': ['85711','84623','88282','85732','88200','42610','85790','84600','84686','42699','88211','42671',
                  '42677','85723','88296'],
     'occupation': ['engineer','librarian','lawyer','scientist','engineer','librarian','artist','engineer','lawyer',
                    'artist','engineer','lawyer','librarian','engineer','scientist'],
     'salary': [np.nan, 23000, 45000, 80000, np.nan, 25000, 30000, 22000, 60000, 43000, 33000, 38000,
                20000, 70000, 45000]})
```

2, Fill the missing value in column `salary` with the **median**. 
 
3, Display the DataFrame, the expected output would be:
    
<img src="//i.imgur.com/U8j3p0A.png" height="40%" width="40%">
</div>

In [76]:
customer_data = pd.DataFrame(
    {'customer_id': [3, 2, 9, 4, 5, 8, 10, 1, 15, 11, 6, 7, 12, 14, 13],
     'gender': ['M','F','M','M','F','M','F','F','F','F','F','M','M','M','F'],
     'customer_age': [22, 21, 35, 40, 22, 28, 25, 43, 33, 37, 27, 30, 20, 50, 32],
     'post_code': ['85711','84623','88282','85732','88200','42610','85790','84600','84686','42699','88211','42671',
                  '42677','85723','88296'],
     'occupation': ['engineer','librarian','lawyer','scientist','engineer','librarian','artist','engineer','lawyer',
                    'artist','engineer','lawyer','librarian','engineer','scientist'],
     'salary': [np.nan, 23000, 45000, 80000, np.nan, 25000, 30000, 22000, 60000, 43000, 33000, 38000,
                20000, 70000, 45000]}) 

In [77]:
customer_data['salary'] = customer_data['salary'].fillna(customer_data['salary'].median())
customer_data

customer_age  customer_id gender occupation post_code   salary
0             22            3      M   engineer     85711  38000.0
1             21            2      F  librarian     84623  23000.0
2             35            9      M     lawyer     88282  45000.0
3             40            4      M  scientist     85732  80000.0
4             22            5      F   engineer     88200  38000.0
5             28            8      M  librarian     42610  25000.0
6             25           10      F     artist     85790  30000.0
7             43            1      F   engineer     84600  22000.0
8             33           15      F     lawyer     84686  60000.0
9             37           11      F     artist     42699  43000.0
10            27            6      F   engineer     88211  33000.0
11            30            7      M     lawyer     42671  38000.0
12            20           12      M  librarian     42677  20000.0
13            50           14      M   engineer     85723  70000.0
14            32           13      F  scientist     88296  45000.0

<div class="alert alert-warning">
<b>QUESTION 16: </b> 

1, Sort the DataFrame `customer_data` by column `customer_id` with ascending order. Then set the column `customer_id` as the index column. 

2, Display the **updated** DataFrame `customer_data`, the expected output would be:
    
<img src="//i.imgur.com/g4svghT.png" height="40%" width="40%">

</div>

In [78]:
customer_data.sort_values('customer_id', ascending=True, inplace=True)
customer_data.set_index('customer_id', inplace=True)
customer_data

customer_age gender occupation post_code   salary
customer_id                                                   
1                      43      F   engineer     84600  22000.0
2                      21      F  librarian     84623  23000.0
3                      22      M   engineer     85711  38000.0
4                      40      M  scientist     85732  80000.0
5                      22      F   engineer     88200  38000.0
6                      27      F   engineer     88211  33000.0
7                      30      M     lawyer     42671  38000.0
8                      28      M  librarian     42610  25000.0
9                      35      M     lawyer     88282  45000.0
10                     25      F     artist     85790  30000.0
11                     37      F     artist     42699  43000.0
12                     20      M  librarian     42677  20000.0
13                     32      F  scientist     88296  45000.0
14                     50      M   engineer     85723  70000.0
15                     33      F     lawyer     84686  60000.0

<div class="alert alert-warning">
<b>QUESTION 17:</b>

1, Add `2` to each value in column `customer_age` from DataFrame `customer_data`.

2, Display the **updated** DataFrame `customer_data`, the expected output would be:
    
<img src="//i.imgur.com/LeBlTzE.png" height="40%" width="40%">

</div>

In [79]:
customer_data['customer_age']+2
customer_data

customer_age gender occupation post_code   salary
customer_id                                                   
1                      43      F   engineer     84600  22000.0
2                      21      F  librarian     84623  23000.0
3                      22      M   engineer     85711  38000.0
4                      40      M  scientist     85732  80000.0
5                      22      F   engineer     88200  38000.0
6                      27      F   engineer     88211  33000.0
7                      30      M     lawyer     42671  38000.0
8                      28      M  librarian     42610  25000.0
9                      35      M     lawyer     88282  45000.0
10                     25      F     artist     85790  30000.0
11                     37      F     artist     42699  43000.0
12                     20      M  librarian     42677  20000.0
13                     32      F  scientist     88296  45000.0
14                     50      M   engineer     85723  70000.0
15                     33      F     lawyer     84686  60000.0

<div class="alert alert-warning">
<b>QUESTION 18: </b> 

Display the matching rows in DataFrame `customer_data` where `post_code` start with `88`, the expected output would be:
    
<img src="//i.imgur.com/Kok6yyu.png" height="40%" width="40%">

</div>
</div>

In [84]:
customer_data.query(customer_data[post_code].startwith ("88"))

NameError: name 'post_code' is not defined

<div class="alert alert-warning">
<b>QUESTION 19: </b> 

1, Calculate the average customer age for each occupation based on DataFrame `customer_data`. 

2, Create a DataFrame called `occupation_age` which has index `occupation` and column `customer_age` with the result from step 1. Display the DataFrame `occupation_age`, the expected output would be:
    
<img src="//i.imgur.com/ynMBXbS.png" height="20%" width="20%">
</div>

<div class="alert alert-warning">
<b>QUESTION 20:</b>

1, Create a new DataFrame called `customer_data_2` which contains rows from DataFrame `customer_data` where `customer_age` are larger or equal to 30.

2, Display the DataFrame `customer_data_2`, the expected output would be:
    
<img src="https://i.imgur.com/GdNsqyC.png" height="40%" width="40%">
</div>